### ISSUE TITLE
Stand autoassignment is bad with bizjets

### ISSUE THREAD

**Issue by pinatacolada** [pinatacolada/topskylppc#104]
sent an AJU citation to 601 thats 🅱️ ad

**Comment by becas22** [comment]
Sent WHT 319 at LPPR to T01. Second assignment sent to S41.

**Comment by becas22** [comment]
Sent SWR A320 to 606 at LPPT. Further assignments were always on apron 60. All the gates were free.

**Comment by pinatacolada** [comment]
ADEP desse swr pls

**Comment by becas22** [comment]
Não me lembro, mas ou era LEBL ou LSZH provavelmente.

Enviado do Correio<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows 10

________________________________
De: pinatacolada <notifications@github.com>
Enviado: Sunday, May 17, 2020 3:55:26 PM
Para: pinatacolada/topskylppc <topskylppc@noreply.github.com>
Cc: becas22 <benyreis@hotmail.com>; Comment <comment@noreply.github.com>
Assunto: Re: [pinatacolada/topskylppc] Stand autoassignment is bad with bizjets (#104)


ADEP desse swr pls
