### ISSUE TITLE
OCEAN32 gets sent to normal aprons

### ISSUE THREAD

**Issue by pinatacolada** [pinatacolada/topskylppc#120]
![imagem](https://user-images.githubusercontent.com/13833056/77855287-5ffcab80-71e7-11ea-8e03-c255b8668011.png)

**Comment by becas22** [comment]
GRadar considers C130 as T.
MIL APN includes T type acft.
Stand 504 uses A and C.
Add OCEAN to MIL APN callsigns?

**Comment by pinatacolada** [comment]
no, otherwise we would need to add in all the tactical callsigns. a more practical solution is probably available, but needs reading into the documentation. iirc gr while first look at all rules, and if it finds nothing matching it drops the callsign rule first

**Comment by pinatacolada** [comment]
relevant part of the manual

> If automatic stand assignment fails to find a suitable stand, the plugin tries again with some restrictions removed (first the CALLSIGN, then also the NOTCALLSIGN, USE, ADEP, NOTADEP, SCHENGEN, NONSCHENGEN, VIA and NOTVIA restrictions are lifted).

so in theory it should assign the military apron by matching with the USE rule, but not in practice, this is where the problem lies

**Comment by pinatacolada** [comment]
#104 probably same issue
