### ISSUE TITLE
INBOUND list may not display when using settings local

### ISSUE THREAD

**Issue by becas22** [pinatacolada/topskylppc#224]
INBOUND list is off by default, on would be noice

**Comment by pinatacolada** [comment]
Its already there
https://github.com/pinatacolada/topskylppc/blob/8856d4247490be3d0dc8ec3f4eb51b59845df472/LPPC/Plugins/topsky/GRpluginSettings.txt#L142
It needs an assigned runway before its displayed

If it doesnt display then, then its a bug

**Comment by becas22** [comment]
A mim não mostra. Podes confirmar?

Enviado do Correio<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows 10

De: pinatacolada<mailto:notifications@github.com>
Enviado: 24 de janeiro de 2021 14:55
Para: pinatacolada/topskylppc<mailto:topskylppc@noreply.github.com>
Cc: becas22<mailto:benyreis@hotmail.com>; Author<mailto:author@noreply.github.com>
Assunto: Re: [pinatacolada/topskylppc] Add INBOUND list to GND RDR (#224)


Its already there
https://github.com/pinatacolada/topskylppc/blob/8856d4247490be3d0dc8ec3f4eb51b59845df472/LPPC/Plugins/topsky/GRpluginSettings.txt#L142
It needs an assigned runway before its displayed

If it doesnt display then, then its a bug

**Comment by pinatacolada** [comment]
![image](https://user-images.githubusercontent.com/13833056/105636517-ac913180-5e60-11eb-8806-362d52356424.png)
ta ok

**Comment by becas22** [comment]
Verifica que é o que tá no GNG e não no master

Enviado do Correio<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows 10

De: pinatacolada<mailto:notifications@github.com>
Enviado: 24 de janeiro de 2021 16:25
Para: pinatacolada/topskylppc<mailto:topskylppc@noreply.github.com>
Cc: becas22<mailto:benyreis@hotmail.com>; Author<mailto:author@noreply.github.com>
Assunto: Re: [pinatacolada/topskylppc] Add INBOUND list to GND RDR (#224)


[image]<https://user-images.githubusercontent.com/13833056/105636517-ac913180-5e60-11eb-8806-362d52356424.png>
ta ok

**Comment by pinatacolada** [comment]
o GNG tb ta actualizado

**Comment by becas22** [comment]
Percebi o problema, tem a ver com o settings local. Vou fazer um pull

**Comment by becas22** [comment]
Percebi o problema, tem a ver com o settings local, está desligado lá

**Comment by pinatacolada** [comment]
ah ja percebi, é preferivel não mexer para prevenir que faça overwrite aos pessoais de alguem, mais vale um mail ou mensagem ou assim a explicar

**Comment by pinatacolada** [comment]
afinal fica aberto ate se explicar lol
