### ISSUE TITLE
BAW at LPPT only gets remote stands assigned by GRPlugin

### ISSUE THREAD

**Issue by becas22** [pinatacolada/topskylppc#240]
title

**Comment by pinatacolada** [comment]
isto e parecido às low costs irem para 12x e 14x, em tempos normais era costume irem para 22x e 80x. se for para corrigir isto acho que se deve por low costs em 14x e 12x tambem

**Comment by becas22** [comment]
Sim, era costume mas também iam para manga acho eu. No grplugin não ta lá definido

Enviado do Correio<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows 10

De: pinatacolada<mailto:notifications@github.com>
Enviado: 2 de março de 2021 14:04
Para: pinatacolada/topskylppc<mailto:topskylppc@noreply.github.com>
Cc: becas22<mailto:benyreis@hotmail.com>; Author<mailto:author@noreply.github.com>
Assunto: Re: [pinatacolada/topskylppc] BAW at LPPT only gets remote stands assigned by GRPlugin (#240)


isto e parecido às low costs irem para 12x e 14x, em tempos normais era costume irem para 22x e 80x. se for para corrigir isto acho que se deve por low costs em 14x e 12x tambem

**Comment by pinatacolada** [comment]
andam em 126, 10x e 14x agora
