### ISSUE TITLE
SAP alert XAMAX1C

### ISSUE THREAD

**Issue by pinatacolada** [pinatacolada/topskylppc#319]

**Comment by becas22** [comment]
![image](https://user-images.githubusercontent.com/11005754/186700083-b26d6db2-d9c7-459f-aa8f-bb56aad8bab0.png)
Afinal parece haver algum problema com o buffer das areas

**Comment by becas22** [comment]
APW_PredictionTime=120                               ->Potencial perf hit. Avaliar custo/beneficio
APW_WarningTime=120
APW_WarningTime_Imm=110
APW_Buffer_Lat_U=3
APW_Buffer_Vert_U=1000
APW_Buffer_Vert_L_IFR=1000
APW_Buffer_Vert_L_VFR=1000
