### ISSUE TITLE
nao da para mostrar next freq na tag

### ISSUE THREAD

**Issue by pinatacolada** [pinatacolada/topskylppc#322]

**Comment by becas22** [comment]
![image](https://user-images.githubusercontent.com/11005754/185586572-f99625b1-f433-470e-b079-c649c090ed8e.png)
maybe this?

**Comment by pinatacolada** [comment]
real:
transfer | toggle freq | manual transfer
assume |                   |

**Comment by becas22** [comment]
Toggle freq -> Toggle SI freq

**Comment by becas22** [comment]
fixed by pr #346
