### ISSUE TITLE
traffic management list - ETO is missing

### ISSUE THREAD

**Issue by becas22** [pinatacolada/topskylppc#354]
source: magic

**Comment by pinatacolada** [comment]
Coluna pls

**Comment by becas22** [comment]
Penso que fique depois do AFL.
A nossa traffic management list é gigante comparada com a deles. A foto que temos deve ser accurate

Enviado do Correio<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows

De: ***@***.***>
Enviado: 26 de agosto de 2022 23:15
Para: ***@***.***>
Cc: ***@***.***>; ***@***.***>
Assunto: Re: [pinatacolada/topskylppc] traffic management list - ETO is missing (Issue #354)


Coluna pls
