### ISSUE TITLE
sector list - runway is missing

### ISSUE THREAD

**Issue by becas22** [pinatacolada/topskylppc#355]
title: ARWY ou algo semelhante
source: magic

**Comment by pinatacolada** [comment]
A coluna fica em que posição?

**Comment by becas22** [comment]
Acho que antes da STAR

Enviado do Correio<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows

De: ***@***.***>
Enviado: 26 de agosto de 2022 23:14
Para: ***@***.***>
Cc: ***@***.***>; ***@***.***>
Assunto: Re: [pinatacolada/topskylppc] sector list - runway is missing (Issue #355)


A coluna fica em que posição?
