### ISSUE TITLE
Inaccurate runway symbol

### ISSUE THREAD

**Issue by pinatacolada** [pinatacolada/topskylppc#371]
mapa de rwys é tipo um retangulo vazio, nao uma linha

_Originally posted by @becas22 in https://github.com/pinatacolada/topskylppc/issues/356#issuecomment-1228969095_

**Comment by becas22** [comment]
BEJA
380348.41N0075603.93W/0.05/275.93
380348.41N0075603.93W
380348.41N0075603.93W/0.05/95.93
380539.70N0075549.30W/0.05/95.93
380539.70N0075549.30W
380539.70N0075549.30W/0.05/275.93
380348.41N0075603.93W/0.05/275.93

LINE:N038.03.48.720:W007.56.07.718:N038.03.48.410:W007.56.03.930
LINE:N038.03.48.410:W007.56.03.930:N038.03.48.101:W007.56.00.143
LINE:N038.03.48.101:W007.56.00.143:N038.05.39.391:W007.55.45.511
LINE:N038.05.39.391:W007.55.45.511:N038.05.39.700:W007.55.49.300
LINE:N038.05.39.700:W007.55.49.300:N038.05.40.010:W007.55.53.089
LINE:N038.05.40.010:W007.55.53.089:N038.03.48.720:W007.56.07.718


CASCAIS
384308.41N0092110.74W/0.05/254.08
384308.41N0092110.74W
384308.41N0092110.74W/0.05/74.08
384346.13N0092124.48W/0.05/74.08
384346.13N0092124.48W
384346.13N0092124.48W/0.05/254.08
384308.41N0092110.74W/0.05/254.08

LINE:N038.43.07.588:W009.21.14.435:N038.43.08.410:W009.21.10.740
LINE:N038.43.08.410:W009.21.10.740:N038.43.09.233:W009.21.07.045
LINE:N038.43.09.233:W009.21.07.045:N038.43.46.953:W009.21.20.785
LINE:N038.43.46.953:W009.21.20.785:N038.43.46.130:W009.21.24.480
LINE:N038.43.46.130:W009.21.24.480:N038.43.45.308:W009.21.28.176
LINE:N038.43.45.308:W009.21.28.176:N038.43.07.588:W009.21.14.435

FARO
370102.00N0075908.21W/0.05/190.07
370102.00N0075908.21W
370102.00N0075908.21W/0.05/10.07
370048.42N0075732.55W/0.05/10.07
370048.42N0075732.55W
370048.42N0075732.55W/0.05/190.07
370102.00N0075908.21W/0.05/190.07

LINE:N037.00.59.049:W007.59.08.867:N037.01.02.000:W007.59.08.210
LINE:N037.01.02.000:W007.59.08.210:N037.01.04.952:W007.59.07.554
LINE:N037.01.04.952:W007.59.07.554:N037.00.51.372:W007.57.31.894
LINE:N037.00.51.372:W007.57.31.894:N037.00.48.420:W007.57.32.550
LINE:N037.00.48.420:W007.57.32.550:N037.00.45.469:W007.57.33.207
LINE:N037.00.45.469:W007.57.33.207:N037.00.59.049:W007.59.08.867

LISBOA
384559.15N0090838.04W/0.05/112.72
384559.15N0090838.04W
384559.15N0090838.04W/0.05/292.72
384732.36N0090748.17W/0.05/292.72
384732.36N0090748.17W
384732.36N0090748.17W/0.05/112.72
384559.15N0090838.04W/0.05/112.72

LINE:N038.45.57.992:W009.08.34.494:N038.45.59.150:W009.08.38.040
LINE:N038.45.59.150:W009.08.38.040:N038.46.00.308:W009.08.41.587
LINE:N038.46.00.308:W009.08.41.587:N038.47.33.518:W009.07.51.718
LINE:N038.47.33.518:W009.07.51.718:N038.47.32.360:W009.07.48.170
LINE:N038.47.32.360:W009.07.48.170:N038.47.31.202:W009.07.44.622
LINE:N038.47.31.202:W009.07.44.622:N038.45.57.992:W009.08.34.494

MADEIRA
324123.75N 0164701.50W/0.05/134.54
324123.75N 0164701.50W
324123.75N 0164701.50W/0.05/314.54
324221.03N 0164554.54W/0.05/314.54
324221.03N 0164554.54W
324221.03N 0164554.54W/0.05/134.54
324123.75N 0164701.50W/0.05/134.54

LINE:N032.41.21.648:W016.46.58.961:N032.41.23.750:W016.47.01.500
LINE:N032.41.23.750:W016.47.01.500:N032.41.25.853:W016.47.04.039
LINE:N032.41.25.853:W016.47.04.039:N032.42.23.133:W016.45.57.080
LINE:N032.42.23.133:W016.45.57.080:N032.42.21.030:W016.45.54.540
LINE:N032.42.21.030:W016.45.54.540:N032.42.18.928:W016.45.52.001
LINE:N032.42.18.928:W016.45.52.001:N032.41.21.648:W016.46.58.961

PORTO
411538.45N 0084104.42W/0.05/258.83
411538.45N 0084104.42W
411538.45N 0084104.42W/0.05/78.83
411401.99N 0084039.13W/0.05/78.83
411401.99N 0084039.13W
411401.99N 0084039.13W/0.05/258.83
411538.45N 0084104.42W/0.05/258.83

LINE:N041.15.37.870:W008.41.08.333:N041.15.38.450:W008.41.04.420
LINE:N041.15.38.450:W008.41.04.420:N041.15.39.031:W008.41.00.508
LINE:N041.15.39.031:W008.41.00.508:N041.14.02.571:W008.40.35.219
LINE:N041.14.02.571:W008.40.35.219:N041.14.01.990:W008.40.39.130
LINE:N041.14.01.990:W008.40.39.130:N041.14.01.410:W008.40.43.041
LINE:N041.14.01.410:W008.40.43.041:N041.15.37.870:W008.41.08.333

PORTO SANTO
330512.94N 0162101.72W/0.05/268.11
330512.94N 0162101.72W
330512.94N 0162101.72W/0.05/88.11
330335.56N 0162057.89W/0.05/88.11
330335.56N 0162057.89W
330335.56N 0162057.89W/0.05/268.11
330512.94N 0162101.72W/0.05/268.11

LINE:N033.05.12.841:W016.21.05.297:N033.05.12.940:W016.21.01.720
LINE:N033.05.12.940:W016.21.01.720:N033.05.13.039:W016.20.58.144
LINE:N033.05.13.039:W016.20.58.144:N033.03.35.659:W016.20.54.315
LINE:N033.03.35.659:W016.20.54.315:N033.03.35.560:W016.20.57.890
LINE:N033.03.35.560:W016.20.57.890:N033.03.35.461:W016.21.01.466
LINE:N033.03.35.461:W016.21.01.466:N033.05.12.841:W016.21.05.297

**Comment by becas22** [comment]
**PORTIMAO**
370901.89N0083518.68W/0.05/197
370901.89N0083518.68W
370901.89N0083518.68W/0.05/17
370854.47N0083449.09W/0.05/17
370854.47N0083449.09W
370854.47N0083449.09W/0.05/197
370901.89N0083518.68W/0.05/197

LINE:N037.08.59.023:W008.35.19.780:N037.09.01.890:W008.35.18.680
LINE:N037.09.01.890:W008.35.18.680:N037.09.04.757:W008.35.17.581
LINE:N037.09.04.757:W008.35.17.581:N037.08.57.337:W008.34.47.991
LINE:N037.08.57.337:W008.34.47.991:N037.08.54.470:W008.34.49.090
LINE:N037.08.54.470:W008.34.49.090:N037.08.51.603:W008.34.50.190
LINE:N037.08.51.603:W008.34.50.190:N037.08.59.023:W008.35.19.780

**PONTE DE SOR**
391215.60N0080342.92W/0.05/114
391215.60N0080342.92W
391215.60N0080342.92W/0.05/294
391308.87N0080312.29W/0.05/294
391308.87N0080312.29W
391308.87N0080312.29W/0.05/114
391215.60N0080342.92W/0.05/114

LINE:N039.12.14.381:W008.03.39.386:N039.12.15.600:W008.03.42.920
LINE:N039.12.15.600:W008.03.42.920:N039.12.16.820:W008.03.46.455
LINE:N039.12.16.820:W008.03.46.455:N039.13.10.090:W008.03.15.825
LINE:N039.13.10.090:W008.03.15.825:N039.13.08.870:W008.03.12.290
LINE:N039.13.08.870:W008.03.12.290:N039.13.07.651:W008.03.08.755
LINE:N039.13.07.651:W008.03.08.755:N039.12.14.381:W008.03.39.386

**SINTRA**
385012.68N0092049.08W/0.05/225.45
385012.68N0092049.08W
385012.68N0092049.08W/0.05/45.45
384931.05N0091956.71W/0.05/45.45
384931.05N0091956.71W
384931.05N0091956.71W/0.05/225.45
385012.68N0092049.08W/0.05/225.45

LINE:N038.50.10.577:W009.20.51.823:N038.50.12.680:W009.20.49.080
LINE:N038.50.12.680:W009.20.49.080:N038.50.14.784:W009.20.46.338
LINE:N038.50.14.784:W009.20.46.338:N038.49.33.154:W009.19.53.968
LINE:N038.49.33.154:W009.19.53.968:N038.49.31.050:W009.19.56.710
LINE:N038.49.31.050:W009.19.56.710:N038.49.28.947:W009.19.59.453
LINE:N038.49.28.947:W009.19.59.453:N038.50.10.577:W009.20.51.823

**ALVERCA**
385225.27N0090216.04W/0.05/122.6
385225.27N0090216.04W
385225.27N0090216.04W/0.05/302.6
385333.56N0090120.14W/0.05/302.6
385333.56N0090120.14W
385333.56N0090120.14W/0.05/122.6
385225.27N0090216.04W/0.05/122.6

LINE:N038.52.23.655:W009.02.12.796:N038.52.25.270:W009.02.16.040
LINE:N038.52.25.270:W009.02.16.040:N038.52.26.886:W009.02.19.284
LINE:N038.52.26.886:W009.02.19.284:N038.53.35.176:W009.01.23.385
LINE:N038.53.35.176:W009.01.23.385:N038.53.33.560:W009.01.20.140
LINE:N038.53.33.560:W009.01.20.140:N038.53.31.945:W009.01.16.895
LINE:N038.53.31.945:W009.01.16.895:N038.52.23.655:W009.02.12.796

**MONTE REAL**
394912.83N 0085315.71W/0.05/91.75
394912.83N 0085315.71W
394912.83N 0085315.71W/0.05/271.75
395032.52N 0085312.56W/0.05/271.75
395032.52N 0085312.56W
395032.52N 0085312.56W/0.05/91.75
394912.83N 0085315.71W/0.05/91.75

LINE:N039.49.12.739:W008.53.11.809:N039.49.12.830:W008.53.15.710
LINE:N039.49.12.830:W008.53.15.710:N039.49.12.922:W008.53.19.612
LINE:N039.49.12.922:W008.53.19.612:N039.50.32.612:W008.53.16.463
LINE:N039.50.32.612:W008.53.16.463:N039.50.32.520:W008.53.12.560
LINE:N039.50.32.520:W008.53.12.560:N039.50.32.429:W008.53.08.658
LINE:N039.50.32.429:W008.53.08.658:N039.49.12.739:W008.53.11.809

**MONTIJO**
384218.02N0090213.81W/0.05/162.44
384218.02N0090213.81W
384218.02N0090213.81W/0.05/342.44
384241.99N0090037.21W/0.05/342.44
384241.99N0090037.21W
384241.99N0090037.21W/0.05/162.44
384218.02N0090213.81W/0.05/162.44

LINE:N038.42.15.162:W009.02.12.651:N038.42.18.020:W009.02.13.810
LINE:N038.42.18.020:W009.02.13.810:N038.42.20.879:W009.02.14.969
LINE:N038.42.20.879:W009.02.14.969:N038.42.44.849:W009.00.38.370
LINE:N038.42.44.849:W009.00.38.370:N038.42.41.990:W009.00.37.210
LINE:N038.42.41.990:W009.00.37.210:N038.42.39.132:W009.00.36.051
LINE:N038.42.39.132:W009.00.36.051:N038.42.15.162:W009.02.12.651

384200.13N0090217.98W/0.05/96.54
384200.13N0090217.98W
384200.13N0090217.98W/0.05/276.54
384310.60N0090207.66W/0.05/276.54
384310.60N0090207.66W
384310.60N0090207.66W/0.05/96.54
384200.13N0090217.98W/0.05/96.54

LINE:N038.41.59.789:W009.02.14.164:N038.42.00.130:W009.02.17.980
LINE:N038.42.00.130:W009.02.17.980:N038.42.00.472:W009.02.21.797
LINE:N038.42.00.472:W009.02.21.797:N038.43.10.942:W009.02.11.478
LINE:N038.43.10.942:W009.02.11.478:N038.43.10.600:W009.02.07.660
LINE:N038.43.10.600:W009.02.07.660:N038.43.10.259:W009.02.03.843
LINE:N038.43.10.259:W009.02.03.843:N038.41.59.789:W009.02.14.164
