### ISSUE TITLE
Areas user text

### ISSUE THREAD

**Issue by pinatacolada** [pinatacolada/topskylppc#382]
notams: MIL
fua: blank?

**Comment by becas22** [comment]
probs

Enviado do Correio<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows

De: ***@***.***>
Enviado: 12 de setembro de 2022 00:59
Para: ***@***.***>
Cc: ***@***.***>
Assunto: [pinatacolada/topskylppc] Areas user text (Issue #382)


notams: MIL
fua: blank?
