### ISSUE TITLE
Missing CPDLC freetexts

### ISSUE THREAD

**Issue by pinatacolada** [pinatacolada/topskylppc#385]

**Comment by becas22** [comment]
quais?

**Comment by rffuret** [comment]
FREETEXT:R:SERVICE TERMINATED FREQ CHG APPROVED

FREETEXT:R:CONTACT ME ON $Freq (não sei se dá, ele ir buscar a frequencia que o ATC tem em uso; sim é uma função real, pelo menos nos temos at MUAC) else FREETEXT:R:CONTACT ME VIA VOICE
