### ISSUE TITLE
Missing tag label toggles

### ISSUE THREAD

**Issue by pinatacolada** [pinatacolada/topskylppc#388]

**Comment by becas22** [comment]
According to ppt:

GS - left click: sep tool;  middle click:highlight;  right click:toggle
ADES - left click: FPL window;  middle click: highlight;  right click:toggle
RFL - left click: RFL menu;  middle click:cpdlc smth;  right click:toggle

Problema é que so temos dois clicks disponiveis. Visto que ja temos o left click para o highlight nos campos em que da, fica o right click para toggle em todos. Problema é que se tiver selecionado o campo no track control, o toggle nao faz nada
