### ISSUE TITLE
Different tag levels have different anchor points

### ISSUE THREAD

**Issue by pinatacolada** [pinatacolada/topskylppc#403]

**Comment by becas22** [comment]
n havia problema de o anchor point nao ser o callsign?

**Comment by pinatacolada** [comment]
nao me lembro, mas todos os niveis tem AFL

**Comment by becas22** [comment]
source?

**Comment by pinatacolada** [comment]
o bug e que passando de detailed para tagged ou untagged ou o que for o anchor muda de elemento o que faz a tag mudar de sitio on mouse over

**Comment by becas22** [comment]
ah então é isso que acontece lol

**Comment by pinatacolada** [comment]
Should be callsign

**Comment by becas22** [comment]
ou entao tem a ver com o next line if not empty

**Comment by pinatacolada** [comment]
tags que saltam:
FPASD, vertical

**Comment by pinatacolada** [comment]
hue havia 1 next line que faltava o if not emtpy
