### ISSUE TITLE
missing plugins

### ISSUE THREAD

**Issue by becas22** [pinatacolada/topskylppc#414]
Also needs updated Euroscope setting to autoload

- [x] #423
- [x] #424
- [ ] https://vatsim-scandinavia.org/forums/topic/3658-maestro-plugin-10/ - loaded but not allowed to draw on screen

**Comment by pinatacolada** [comment]
O vatcan pode ser incluido, mad nao e para desenhar no ecra. Nao se vai ter um plugin que so se uda uma vez por ano a ocupar espaco de ecra. Quando for eventos para se usar autoriza se o draw. 
Maestro nao faz parte nem e para fazer.

**Comment by becas22** [comment]
o vatcan foi o que disse
O maestro vai ser implementado mais tarde, assim ficava logo

**Comment by pinatacolada** [comment]
Quando e se for implementado na altura adiciona se, nao se vai adicionar coisas que nao sao para usar
