### ISSUE TITLE
move lines from maps.txt to sct

### ISSUE THREAD

**Issue by becas22** [pinatacolada/topskylppc#427]
and then use sctdata to load them to maps

**Comment by pinatacolada** [comment]
Label de tweak e no pr senao aparece no changelog

**Comment by becas22** [comment]
`The SctData line is used to draw items from the active sector file data. Specifying only the Type or Group will draw all items. Due to limitations in the data available from EuroScope, the drawing will only look correct when an item contains a single polygon or polyline with the points in consecutive order. The items are drawn using the current map line style and color regardless of what is specified in the sector file.`

Devido a isto, temos que ter atenção à maneira como se põe os itens no SCT File
