### ISSUE TITLE
LPPT Ground Map T2 block

### ISSUE THREAD

**Issue by rffuret** [pinatacolada/topskylppc#451]
quando se abre a view de Lisboa, o block da taxiway T2 "pisca" sempre para carregar
Mais estranho ainda, é que activando o LVP, ele desaparece por completo
![image](https://user-images.githubusercontent.com/29098568/193063453-f9e960e9-4cb7-444e-a208-6656540f96d2.png)
![image](https://user-images.githubusercontent.com/29098568/193063491-3ac4e9f5-091b-42a0-8686-efa7e7756178.png)

**Comment by becas22** [comment]
Isso é porque essa taxiway está fechada quando nao está LVP. O piscar é o plugin a carregar
