### ISSUE TITLE
analisar hipotese de adicionar radar holes nos aeroportos

### ISSUE THREAD

**Issue by becas22** [pinatacolada/topskylppc#464]
- não ver avioes no chão
- realistic coasting symbol approaching the rwy

to check: ground radar radars

**Comment by becas22** [comment]
![image](https://user-images.githubusercontent.com/11005754/194346930-3c675ba6-029b-4ae5-abdf-232b8b9026f8.png)
Com estes settings é possivel tirar os radares de solo do .ese

Deixam de aparecer avioes no chão e ficam com o símbolo de coasting a chegar #maximumrealism

**Comment by becas22** [comment]
@pinatacolada quando podemos testar isto?

**Comment by pinatacolada** [comment]
Not a priority rn
