### ISSUE TITLE
R60BU needs trimming

### ISSUE THREAD

**Issue by pinatacolada** [pinatacolada/topskylppc#471]
![311928381_2556525237819098_8824010994637837471_n](https://user-images.githubusercontent.com/13833056/196930926-1aee1354-2827-4ef3-82e9-4bf6ba22b521.jpg)
![unknown](https://user-images.githubusercontent.com/13833056/196930988-8a2a9d16-ee5b-4e6c-aa3e-de12fc1b8433.png)
 chop chop

**Comment by becas22** [comment]
Cheira-me que isto foi um acordo pontual por causa da implementação to toplis para diminuir atrasos e deixar usar a 1C/9D. Acho que se pode fechar para já visto que as fontes recentes têm a área normal

**Comment by pinatacolada** [comment]
Nessas todas e R60BL, a que interessa é a 60BU

**Comment by becas22** [comment]
Isto ainda é assim
PR incoming soon TM

**Comment by pinatacolada** [comment]
Sauce?

**Comment by becas22** [comment]
chef secret
