### ISSUE TITLE
Unit indicator wrong position in tag

### ISSUE THREAD

**Issue by pinatacolada** [pinatacolada/topskylppc#490]
should be first element of line 0 and added 2+ option if avail in tagged

**Comment by becas22** [comment]
pode-se usar a dev version do topsky e a tag family criada por ele para fazer x-check

**Comment by pinatacolada** [comment]
os tag items sao diferentes/novos

**Comment by becas22** [comment]
Ya mas dá para ter uma ideia

Enviado do Correio<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows

De: ***@***.***>
Enviado: 3 de novembro de 2022 23:31
Para: ***@***.***>
Cc: ***@***.***>; ***@***.***>
Assunto: Re: [pinatacolada/topskylppc] Unit indicator wrong position in tag (Issue #490)


os tag items sao diferentes/novos

**Comment by pinatacolada** [comment]
ja tentei, nao da para comparar. ja marquei as diferencas todas ao longo das issues
