### ISSUE TITLE
Simulated traffic symbology

### ISSUE THREAD

**Issue by becas22** [pinatacolada/topskylppc#507]
Como temos a symbology do Euroscope toda a branco, o simulated traffic fica sem target
![image](https://user-images.githubusercontent.com/11005754/200615140-0af042eb-64fe-43c7-896b-9cfb47398971.png)

**Comment by becas22** [comment]
Btw, isso está com leader line porque o truque do leader a 0 no asr não está a funcionar. Já vejo a alternativa

**Comment by pinatacolada** [comment]
essa foto tem tags Matias e nao topsky

**Comment by becas22** [comment]
Tens razão

**Comment by pinatacolada** [comment]
nao, o fpasd tem um filtro interno, so fpl que no minimo sejam concerned e que sao visiveis. para alem disso, o simulated traffic contribui para a atribuicao de squawks
