### ISSUE TITLE
CARD Settings

### ISSUE THREAD

**Issue by pinatacolada** [pinatacolada/topskylppc#521]
ctr:
![image](https://user-images.githubusercontent.com/13833056/202257801-7fcc472f-4dbd-4215-a029-2c732e2ddec2.png)

app:
![image](https://user-images.githubusercontent.com/13833056/202256971-60d22f1e-048e-4cf6-83a9-ef784f7923a8.png)

**Comment by becas22** [comment]
Não são iguais?

**Comment by pinatacolada** [comment]
fiz mal o copy paste

**Comment by pinatacolada** [comment]
No settings as of 2.4.1

`FPCP_MinState=0` half assed to at least show unco to app
