### ISSUE TITLE
APP CPDLC does not suggest correct logon code

### ISSUE THREAD

**Issue by pinatacolada** [pinatacolada/topskylppc#531]
suggests LPPT instead of LPYL for example

**Comment by becas22** [comment]
Usar LOGON tipo LPPR, LPFR, LPMA para estes aeroportos que não têm DCL
Cria problema de consistência com Lisboa

**Comment by pinatacolada** [comment]
Nao é solução

**Comment by pinatacolada** [comment]
Might be fixed

**Comment by becas22** [comment]
I confirm fixed
