### ISSUE TITLE
SEP Tool colour when invoked from CARD

### ISSUE THREAD

**Issue by becas22** [pinatacolada/topskylppc#542]
Quando se invoca a SEP Tool através do CARD (right click no ID do CARD) a SEP Tool aparece no ecrã praticamente na mesma cor do background

**Comment by becas22** [comment]
Needs Color_CARD_Min_Sep

**Comment by pinatacolada** [comment]
devia ser Color_SEP_Tool_x

**Comment by pinatacolada** [comment]
isso muda a cor da janela do card
