### ISSUE TITLE
Ground radar sem labels/general bugs/config

### ISSUE THREAD

**Issue by becas22** [pinatacolada/topskylppc#571]
O que antes acontecia com alguns avioes, agora esta a acontecer com todos, nao tem label a nao ser com mouse hover na barra

**Comment by becas22** [comment]
Provavelmente relacionado com o "assume acft on gnd as stby"

**Comment by becas22** [comment]
Temos de desligar essa opção e voltar a por o filtro de altitude no ASR

**Comment by becas22** [comment]
E sugiro voltar aos radares pelo ESE, alguma coisa não ficou a funcionar a 100%

**Comment by becas22** [comment]
Após falar com o Juha, o problema deve ser de se ter introduzido radar modo-s. Aquele simbolo (quadrado) na verdade é o retorno do XPDR modo S, mas pode estar em standby.
Sugiro deixar esta issue aberta até percebemos bem os settings que temos e que está tudo a funcionar.
Also, nos aeroportos que não tem ground radar as cores estão funky

**Comment by pinatacolada** [comment]
e esta tudo a funcionar... as cores diferentes sao intencionais para ser mais visivel e distingue dep/arr/outros
