### ISSUE TITLE
Sector list SI collumn too smol

### ISSUE THREAD

**Issue by pinatacolada** [pinatacolada/topskylppc#618]
![image](https://user-images.githubusercontent.com/13833056/219766190-441cd2d4-16fe-4f07-b461-e4f7e759b48a.png)

**Comment by becas22** [comment]
Isto era por design, porque a coluna do SI tem 7 caracteres. A alternativa é passar para 9 para este caso em especifico

**Comment by becas22** [comment]
Afinal diria que o real são 8, portanto passar para 9 não é assim tão chocante
