### ISSUE TITLE
Change RET speed on ese file

### ISSUE THREAD

**Issue by Supercau03** [pinatacolada/topskylppc#672]
Velocidade dos RET aumentado de 35 para 50 kts para ajudar aviões a sair da pista

Tens aqui os novos parametros para o ese:

[GROUND]
EXIT:02:H4:RIGHT:50
COORD:N038.46.53.793:W009.08.08.817
COORD:N038.46.55.066:W009.08.07.785
COORD:N038.46.56.326:W009.08.06.876
COORD:N038.46.57.540:W009.08.05.666
COORD:N038.46.58.475:W009.08.04.625
COORD:N038.47.01.320:W009.08.00.785
COORD:N038.47.01.647:W009.07.59.874
COORD:N038.47.01.652:W009.07.59.224
COORD:N038.47.01.476:W009.07.58.481
COORD:N038.47.01.054:W009.07.57.891
COORD:N038.47.00.515:W009.07.57.453
COORD:N038.46.59.946:W009.07.57.424
COORD:N038.46.59.589:W009.07.57.471
COORD:N038.46.57.946:W009.07.58.348

EXIT:02:U5:RIGHT:20
COORD:N038.47.04.986:W009.08.02.820
COORD:N038.47.05.759:W009.08.02.418
COORD:N038.47.05.977:W009.08.02.305
COORD:N038.47.06.301:W009.08.02.021
COORD:N038.47.06.491:W009.08.01.893
COORD:N038.47.06.758:W009.08.01.581
COORD:N038.47.06.904:W009.08.01.390
COORD:N038.47.07.098:W009.08.00.999
COORD:N038.47.07.293:W009.08.00.609
COORD:N038.47.07.430:W009.08.00.046
COORD:N038.47.07.490:W009.07.59.464
COORD:N038.47.07.478:W009.07.58.805
COORD:N038.47.07.371:W009.07.58.282
COORD:N038.47.07.113:W009.07.57.721
COORD:N038.47.06.820:W009.07.57.266
COORD:N038.47.06.133:W009.07.56.610
COORD:N038.47.05.519:W009.07.56.379
COORD:N038.47.04.874:W009.07.56.193
COORD:N038.47.03.888:W009.07.55.895
COORD:N038.47.03.262:W009.07.55.902
COORD:N038.47.02.748:W009.07.55.967
COORD:N038.47.02.358:W009.07.56.054
COORD:N038.47.01.664:W009.07.56.414

EXIT:02:S4:LEFT:20
COORD:N038.47.48.232:W009.07.39.707
COORD:N038.47.48.513:W009.07.39.561
COORD:N038.47.48.936:W009.07.39.487
COORD:N038.47.49.199:W009.07.39.497
COORD:N038.47.49.402:W009.07.39.538
COORD:N038.47.49.706:W009.07.39.673
COORD:N038.47.49.988:W009.07.39.878
COORD:N038.47.50.291:W009.07.40.219
COORD:N038.47.50.441:W009.07.40.522
COORD:N038.47.50.610:W009.07.40.815
COORD:N038.47.50.806:W009.07.41.328
COORD:N038.47.51.092:W009.07.42.176
COORD:N038.47.51.850:W009.07.44.566

EXIT:20:H1:LEFT:50
COORD:N038.46.44.777:W009.08.13.649
COORD:N038.46.43.790:W009.08.14.138
COORD:N038.46.42.791:W009.08.14.588
COORD:N038.46.41.282:W009.08.14.926
COORD:N038.46.39.846:W009.08.15.203
COORD:N038.46.38.778:W009.08.15.336
COORD:N038.46.37.721:W009.08.15.393
COORD:N038.46.29.974:W009.08.15.082
COORD:N038.46.29.055:W009.08.15.044
COORD:N038.46.27.647:W009.08.14.955
COORD:N038.46.26.727:W009.08.15.081
COORD:N038.46.26.418:W009.08.15.172
COORD:N038.46.25.397:W009.08.15.726

EXIT:20:H3L:RIGHT:50
COORD:N038.46.33.638:W009.08.19.589
COORD:N038.46.33.148:W009.08.19.815
COORD:N038.46.31.643:W009.08.20.040
COORD:N038.46.30.018:W009.08.20.328
COORD:N038.46.28.043:W009.08.20.416
COORD:N038.46.20.444:W009.08.20.057
COORD:N038.46.19.445:W009.08.19.961
COORD:N038.46.17.796:W009.08.19.968
COORD:N038.46.17.212:W009.08.20.125
COORD:N038.46.16.802:W009.08.20.309
COORD:N038.46.16.690:W009.08.20.397

EXIT:20:H3G:RIGHT:50
COORD:N038.46.33.575:W009.08.19.681
COORD:N038.46.31.466:W009.08.20.074
COORD:N038.46.29.941:W009.08.20.309
COORD:N038.46.27.857:W009.08.20.425
COORD:N038.46.21.835:W009.08.20.126
COORD:N038.46.21.428:W009.08.19.898
COORD:N038.46.21.219:W009.08.19.626
COORD:N038.46.21.006:W009.08.19.414
COORD:N038.46.20.828:W009.08.19.096
COORD:N038.46.20.784:W009.08.18.826
COORD:N038.46.20.678:W009.08.18.441
COORD:N038.46.20.676:W009.08.17.944
COORD:N038.46.20.828:W009.08.17.133

EXIT:20:H3:LEFT:50
COORD:N038.46.33.626:W009.08.19.625
COORD:N038.46.33.119:W009.08.19.800
COORD:N038.46.31.878:W009.08.20.035
COORD:N038.46.30.344:W009.08.20.246
COORD:N038.46.29.315:W009.08.20.341
COORD:N038.46.27.829:W009.08.20.410
COORD:N038.46.21.847:W009.08.20.090
COORD:N038.46.20.047:W009.08.20.000
COORD:N038.46.19.142:W009.08.19.972

EXIT:20:P:LEFT:20
COORD:N038.46.20.381:W009.08.26.700
COORD:N038.46.19.851:W009.08.26.975
COORD:N038.46.19.522:W009.08.27.005
COORD:N038.46.18.887:W009.08.26.913
COORD:N038.46.18.510:W009.08.26.804
COORD:N038.46.17.911:W009.08.26.483
COORD:N038.46.17.417:W009.08.25.966
COORD:N038.46.17.024:W009.08.25.303
COORD:N038.46.16.763:W009.08.24.641
COORD:N038.46.16.138:W009.08.22.505

EXIT:20:N2:LEFT:20
COORD:N038.46.00.542:W009.08.37.175
COORD:N038.46.00.391:W009.08.37.193
COORD:N038.46.00.106:W009.08.37.207
COORD:N038.45.59.788:W009.08.37.161
COORD:N038.45.59.555:W009.08.37.042
COORD:N038.45.59.172:W009.08.36.837
COORD:N038.45.59.002:W009.08.36.655
COORD:N038.45.58.661:W009.08.36.217
COORD:N038.45.58.501:W009.08.35.850
COORD:N038.45.57.302:W009.08.32.287

EXIT:20:M5:LEFT:20
COORD:N038.45.58.484:W009.08.38.379
COORD:N038.45.58.104:W009.08.38.472
COORD:N038.45.57.707:W009.08.38.513
COORD:N038.45.57.519:W009.08.38.491
COORD:N038.45.57.284:W009.08.38.403
COORD:N038.45.57.068:W009.08.38.335
COORD:N038.45.56.779:W009.08.38.125
COORD:N038.45.56.364:W009.08.37.680
COORD:N038.45.56.193:W009.08.37.424
COORD:N038.45.54.958:W009.08.33.685

**Comment by pinatacolada** [comment]
isto nao faz os avioes fazerem a curva do H4 a 50 nos?

**Comment by Supercau03** [comment]
Do meu entender é a velocidade maxima para o avião fazer vacate ou n 
![Screenshot_20230710_172913_Chrome](https://github.com/pinatacolada/topskylppc/assets/33237159/7021589e-8b07-424a-a9bd-5674c8ba409a)

**Comment by pinatacolada** [comment]
ok, os 50 nós aplicam-se no inicio da RET quando se desvia da centerline, com uma desacelaração continua até taxi speed.

especificamente em lisboa, as RET estão desenhadas com 30 nós maximo.

![image](https://github.com/pinatacolada/topskylppc/assets/13833056/b6e3ff6a-39f6-41a1-8000-e16eb7fd95ab)

**Comment by Supercau03** [comment]
Entendo mas a problema é que o Euroscope parace fazer a decisão de entrar ou não na RET muito cedo. Eu antes tinha aquilo configurado para 35 e tinhas alguns aviões a falhar a saida a uma velocidade totalmente normal. Estive a experimentar no meu euroscope e 50 parece dar um comportamento parecido com aquilo que vemos na rede. Da mesma forma que configurei as saidas normais a 20kts sabendo muito bem que só um maluco sai a essa velocidade .

**Comment by pinatacolada** [comment]
com este codigo a que velocidade e que fazem a curva do H4 ou as partes finais dos outros?

**Comment by Supercau03** [comment]
![image](https://github.com/pinatacolada/topskylppc/assets/33237159/4bb8bd22-8e9e-47b4-b3db-b8a55616bd84)
![image](https://github.com/pinatacolada/topskylppc/assets/33237159/6331e562-cbd9-4c6c-a026-c5714cc2e3ed)
![image](https://github.com/pinatacolada/topskylppc/assets/33237159/29b7f5a0-a544-468f-ab59-47726091be28)

**Comment by pinatacolada** [comment]
too fast, 15kt maximo, maximo absoluto 20, no inicio da curva a serio. talvez encurtando o segmento de RET até antes da curva seja o suficiente para os encorajar a desacelarar como deve de ser
