### ISSUE TITLE
ADS 10B codes not recognized as mode S capable

### ISSUE THREAD

**Issue by pinatacolada** [pinatacolada/topskylppc#815]
![image](https://github.com/user-attachments/assets/2db4bcf9-29a5-448d-995b-e9fa2d8533c3)

**Comment by becas22** [comment]
Acho que está correto. Transponder S não tem EHS

**Comment by becas22** [comment]
Entretanto verifiquei, os tracks exclusivos ads-b não têm DAPs

**Comment by pinatacolada** [comment]
o bug nao e daps, o euroscope trata o voo como so tendo modo C

**Comment by becas22** [comment]
Então mas o RPS não é se é modo S ou não, é se tem DAPS ou nao
